### ISSUE TITLE
Incompatibility with vim-fugitive, using dein

### ISSUE THREAD

**Issue by CharlesGueunet** [tpope/vim-commentary#109]
Hello and first of all thanks for all your great work on vim !

I use dein as my package manager and I have found an issue concerning both vim-commentary and vim-fugitive. Fortunately, you are the author of both :)

If I add vim-commentary in my plugin list, then vim-fugitive is loaded but none of these functions are available (`:Ggrep` -> `E492: Not an editor command: Ggrep`).

I will try to investigate further when I have the time (and post more details here).
If you have any idea of what could cause this issue, that could help me.

Thank again!
Charles

**Comment by tpope** [comment]
You do have a file from a Git repository open, correct?

**Comment by CharlesGueunet** [comment]
Yes, with visible changes given by gitgutter.

**Comment by tpope** [comment]
Strange is an understatement. I don't have any great advice but my first step would be to check `:scriptnames` and make sure everything's there. You might also try rearranging the order of your dein declarations.

**Comment by CharlesGueunet** [comment]
I am still investigating here:
* the plugin [commitia](https://github.com/rhysd/committia.vim) is also impacted, which let me think the problem should come from either dein or commentary.
* it seems the principal symptom is that `automcd VimEnter *` ... inside commitia or fugutive are not executed when commentary is enabled. I still need to understand why.

**Comment by CharlesGueunet** [comment]
This is due to a configuration I did for commentary (so my mistake !)
Trying to define '# ' as the default commentstring, I had this line in an augroup:
```vim
autocmd BufNewFile,BufRead * if empty(&filetype) | setlocal commentstring=#\ %s 
```
Replacing it with:
```vim
autocmd BufNewFile,BufRead * if !exists('b:commentary_format') | setlocal commentstring=#\ %s  
```
solve the issue !

Thanks for your help :)

**Comment by tpope** [comment]
My personal solution:

```viml
setglobal commentstring=#\ %s
autocmd FileType c,cpp,cs,java setlocal commentstring=//\ %s
```
