### ISSUE TITLE
dic / dc (and maybe  yic/ pic / yc / pc)

### ISSUE THREAD

**Issue by loshjawrence** [tpope/vim-commentary#111]
I was hoping this plugin supported something like `dic`/`yic`/`pic` but it appears it does not.
If the cursor is in a contiguous set of single comments or a comment block it would be nice to support `c` as a text object for comments. I think `dc`/`yc`/`pc` should only affect the line the cursor is on, otherwise for the inner motion versions do something like the cases below. 

Also, I think contiguous inline vs contiguous not-inline should be distinguished since I think most of the time this non-greedy approach is likely the intention of the user... and if the user wanted the greedy behavior they can just follow up with a `.` repeat.

`cic` could work but `cc` wouldn't follow the convention since it's already a core operation.

```
int y = 0; // Don't touch. 
// Touch
// Touch  // Cursor on inner 3 lines
// Touch
int x = 0; // Don't touch.
```

```
int y = 0;  // Don't touch.
/********************
 Touch. Cursor somewhere on the block comment
********************/ 
int x =0; // Don't touch.
```

```
int x =0; // Touch.
int y =0; // Touch. // Cursor on upper 3 lines
int z =0; // Touch.
// Don't touch
// Don't touch
// Don't touch
```

**Comment by xaizek** [comment]
> I was hoping this plugin supported something like `dic`/`yic`/`pic` but it appears it does not.

Try <kbd>dgc</kbd>, etc.

Note that commentary does only whole line commenting, so your second and third examples don't work.

**Comment by loshjawrence** [comment]
'dgc' doesn't work for me. I tried vim-plug's :PlugClean and :PlugInstall but it still doesn't work, also checked my tagbar in my vimrc to make sure dgc isn't mapped to something else.

**Comment by xaizek** [comment]
It uses value of `'commentstring'` option, you can change it to
```vim
setlocal commentstring=//\ %s
```
and it will work on `// comment`, but not on `/* comment */`.

**Comment by tpope** [comment]
Yep, `dgc` will delete comments created by `gc`. Commentary does not - and likely will never - support arbitrary comment syntax.

**Comment by loshjawrence** [comment]
Awesome thanks. This gets me what I need.
Plug 'tpope/vim-commentary'
autocmd FileType c,cpp,javascript,json setlocal commentstring=//\ %s
