### ISSUE TITLE
Wrong comment symbols with desktop entry (.desktop) files

### ISSUE THREAD

**Issue by sdicke** [tpope/vim-commentary#114]
Expected: Commented out lines start with #
Plugin behavior: Commented out lines start with /* and end with */

Specification of the comment format: https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html#comments

**Comment by chrisbra** [comment]
https://github.com/tpope/vim-commentary#faq

**Comment by tpope** [comment]
There's no `ftplugin/desktop.vim` in Vim. It would be cool if one submitted one to Bram!
