### ISSUE TITLE
Add option to comment blank lines

### ISSUE THREAD

**Issue by anuvyklack** [tpope/vim-commentary#116]
It would be great if there was an opportunity to comment out empty lines when commenting a region.

It will be useful, for example in python where blank lines separate different blocks of code. You select a function, comments it out and if all blank lines are also commented, then you can uncomment the whole function with just `gcip`. Now I have to either visually select whole function body and press `gc`, or manually uncomment each block.

**Comment by tpope** [comment]
You can uncomment multiple consecutive "comment paragraphs" with `gcgc`. Blank comments are a little weird and raise whitespace questions; I do not intend to add them at this time.

**Comment by casey** [comment]
This would be nice! In particular, if you comment out a block which contains empty lines, you can then use paragraph `{` / `}` motions to uncomment them, which otherwise wouldn't get the whole thing, since it would contain empty lines.
