### ISSUE TITLE
Commenting a comment in a react component breaks source file

### ISSUE THREAD

**Issue by preslavmihaylov** [tpope/vim-commentary#117]
Given the file:
```js
// @flow
import * as React from 'react';

export default function Foo() {
  return (
    <div>
      {/* some comment */}
      <div>Bar</div>
    </div>
  );
}
```

Do steps:
1. Visual-select the comment line and the `Bar` line
2. Comment the lines using `vim-commentary` (`gc`)

Result:
```js
// @flow
import * as React from 'react';

export default function Foo() {
  return (
    <div>
      {/* {1/* some comment */1} */}
      {/* <div>Bar</div> */}
    </div>
  );
}
```

The comment line is broken and I have to manually go and fix it.

I expected the commented comment to look like this:
```
{/* {/* some comment *\/} */}
```

**Comment by tpope** [comment]
Uncommenting undoes it. What's wrong with Commentary's syntax, and how is it supposed to know you prefer a different syntax?

**Comment by preslavmihaylov** [comment]
The react component doesnt render with this syntax

**Comment by tpope** [comment]
I suppose non-functioning code is a valid concern. Would changing it to `{/1* ... *1/}` do the trick?

**Comment by preslavmihaylov** [comment]
Here's how the component renders without commenting anything:
![image](https://user-images.githubusercontent.com/7642330/68010071-42ed9c00-fc8c-11e9-9dc2-28fbd90d0907.png)

Here's how it renders after commenting the lines mentioned out:
![image](https://user-images.githubusercontent.com/7642330/68010089-56990280-fc8c-11e9-98d1-115ee6758cfd.png)

The suggestion you made works and the component is rendered properly this way:
![image](https://user-images.githubusercontent.com/7642330/68010187-9c55cb00-fc8c-11e9-85f0-ca49adfc7b65.png)

(a blank page is expected)
