### ISSUE TITLE
Installation instructions for people who already use git for their config files

### ISSUE THREAD

**Issue by PeterJRiches** [tpope/vim-commentary#127]
### Problem
The current installation instructions clone from this repository into the user's .vim configuration directory structure, and that works great if the user is not already using git to look after their configs, like I do. The problem with this repo being cloned within an outer repo is that git can assume that the inner repo is a malformed or incomplete `git submodule`. (I deleted the commentary repo when this happened to me, and modified my method of installation as below.)

### Proposal
For people who use git to oversee their configs, the following two lines can replace the `git clone...` command in the installation instructions in README.markdown:
`git submodule add https://tpope.io/vim/commentary.git commentary`
`git commit -m"Added Vim commentary plugin as a git submodule."`

**Comment by tpope** [comment]
If this is your preferred management system, you already know how to do this. I'm not wasting precious README space telling people what they already know.

P.S. Don't use periods in your commit message. It makes you look like a psychopath.
