### ISSUE TITLE
Is there a way to put the comment character in the first column?

### ISSUE THREAD

**Issue by gfixler** [tpope/vim-commentary#14]
I tried `^#\ *%s`, but I guess it's not a regex. I'm in Python, and having `#` characters at a mix of indentation levels is a little confusing. I've been using a pair of mapped regexes to do this for awhile, but I like commentary's toggle abilities and operator-pending mode.

**Comment by ecerulm** [comment]
Nowadays you have `b:commentary_startofline=1` to do this. You can have something like this is your vimrc configuration

```
autocmd FileType terraform setlocal commentstring=#\ %s
autocmd FileType terraform let b:commentary_startofline=1
```
