### ISSUE TITLE
How to set .vimrc file to use `"` commentstring?

### ISSUE THREAD

**Issue by Blake-LeBlanc** [tpope/vim-commentary#140]
When commenting .vimrc file, vim-commentary is using `#` instead of `"`. 

Is there anything I can do to change that?

Thank you!

**Comment by chrisbra** [comment]
I think that might depend on whether vim detects vim filetype as Vim 9 script or legacy vim script. Check your ftplugin/vim.vim runtime file. 

However, you might be able to customize the commentstring option in an after directory.

**Comment by JESii** [comment]
Been frustrated about this for quite a while -- not a very helpful response -- so I switched to `tcomment.vim` which works flawlessly out of the box. 

I still have 20+ tpope plugins which are awesome - thanks!
