### ISSUE TITLE
Autocmd doasn't work

### ISSUE THREAD

**Issue by Murtrag** [tpope/vim-commentary#141]
I get a wrong comment type in pascal files
```
:verbose setlocal commentstring?
 commentstring=/*%s*/

:set filetype?
filetype=pascal
```

so I've tried

```
:autocmd FileType setlocal commentstring={ %s }
:autocmd FileType pascal commentstring={ %s }
```
but commentstring is still the sam

**Comment by tpope** [comment]
```vim
autocmd FileType pascal setlocal commentstring={\ %s\ }
```

**Comment by Murtrag** [comment]
Unfortunately it doesn't help either, I don't get any errors, it just doesn't change anything.
For now, I use
`verbose set commentstring={ %s }`

**Comment by tpope** [comment]
You can also try adding `setlocal commentstring={\ %s\ }` to `~/.vim/after/ftplugin/pascal.vim`.

**Comment by Murtrag** [comment]
Thanks this way works!
