### ISSUE TITLE
toml uses wrong syntax

### ISSUE THREAD

**Issue by paperbenni** [tpope/vim-commentary#143]
when commenting stuff in toml it uses a c like syntax when it actually should be doing shell-like comments

expected:  
![image](https://user-images.githubusercontent.com/15818888/116598796-909da000-a927-11eb-908b-e3c2d0581c05.png)

vim-commentary:
![image](https://user-images.githubusercontent.com/15818888/116599014-d6f2ff00-a927-11eb-9092-7741b45c0f78.png)

**Comment by xaizek** [comment]
https://github.com/tpope/vim-commentary#faq

**Comment by paperbenni** [comment]
fair enough, but I feel like toml is big enough to warrant out of the box support

**Comment by paperbenni** [comment]
oh, I thought the plugin was handling the syntax by itself, looks like it's done by vim
