### ISSUE TITLE
Is it possible to change the comment style for some filetype?

### ISSUE THREAD

**Issue by hongxuchen** [tpope/vim-commentary#15]
I am annoyed that C/C++ files are always commented with `/* .. */`, while I hope there could be one line comment. Also some comments are not right set by default, for instance, I cannot get the right comment in elisp files(filetype:lisp). So is it possible to customize?

**Comment by heefan** [comment]
I set as `//` for c/cpp, but it doesn't work, may I know how to fix it? Thanks

    autocmd FileType c,cpp,java setlocal commentstring=//\ %s

**Comment by xaizek** [comment]
@heefan, try running `:verbose setlocal commentstring?` it will show you from where `'commentstring'` was set last time.

**Comment by heefan** [comment]
@xaizek, sorry for late reply. 
It works actually. I think I opened too many consoles with vim ;) .
Thanks again.

**Comment by ritiek** [comment]
For some reason I had to use `set` instead of `setlocal` on NeoVim for it to work.

**Comment by aq2** [comment]
Old issue i know, but i'm having trouble with stylus .styl files. (stylus is a css preprocessor similar to sass, but even more sassy and far more stylish)

Anyway, i'm currently getting html stlye `<!-- -->` comments, but i want to use `//`

i've tried ` autocmd FileType styl setlocal commentstring=//\ %s`
in both my vimrc, and /ftplugin/styl .vim, but it don't work.

`:verbose setlocal commentstring?` returns .../vim81/ftplugin/html.vim

how do i fix?  thanks

or might this be a problem with the iloginow/vim-stylus syntax plugin?

**Comment by tpope** [comment]
It should work if you put it in `.vim/after/ftplugin/styl.vim`.

**Comment by aq2** [comment]
thanks for the quick reply, but unfortunately it still does not work, i'm still getting html style comments in .styl files

**Comment by graywh** [comment]
also check `verbose set filetype?` after you open a .styl file

**Comment by aq2** [comment]
thanks @graywh - i've already reported that tht verbose... command returns
`last set from /usr/share/vim/vim81/ftplugin/html.vim`

**Comment by aq2** [comment]
if i set the comment string manually from the command line when editing .styl files, then the commentstring is correct.

unfortunately the autocmd doesn't seem to work

**Comment by graywh** [comment]
You misread what I said.  It's a different command.

`ftplugin/htm.vim` is being loaded *because* `filetype=html` so you need to determine why it's `html` instead of `styl`.

**Comment by aq2** [comment]
ah sorry, i did indeed misread

`filetype=stylus  Last set from ~/vim/plugged/vim-stylus/ftdetect/stylus.vim`

**Comment by tpope** [comment]
In a brand new Vim instance, edit a styl file and check the order of all `ftplugin/html.vim` and `ftplugin/styl.vim` files in `:scriptnames`. The goal is to get your after file to be the last one.

**Comment by aq2** [comment]
interesting:

the `after/ftplugin/styl.vim` doesn't seem to get loaded at all, so i changed the name to stylus.vim, which now gets loaded at 111/117, indeed it is after `vim81/ftplugin/html` at 109

output of :scriptnames:

    ...snip
    107: ~/.vim/plugged/vim-stylus/syntax/stylus.vim
    108: ~/.vim/plugged/vim-stylus/ftplugin/stylus.vim
    109: /usr/share/vim/vim81/ftplugin/html.vim
    110: /usr/share/vim/vim81/autoload/htmlcomplete.vim
    111: ~/.vim/after/ftplugin/stylus.vim 
    112: ~/.vim/plugged/vim-stylus/indent/stylus.vim
    113-117 ...gitgutter stuff
    ..end of output

i tried putting the autocmd to set commentstrings in `after/ftplugin/stylus.vim`, but still no luck

**Comment by xaizek** [comment]
If file type is called `stylus`, you should use `stylus` instead of `styl` in your autocmd as well.

**Comment by aq2** [comment]
thanks @xaizek , but i've tried that too!

    autocmd FileType stylus setlocal commentstring=//\ %s

**Comment by xaizek** [comment]
Another suggestion: try running `:autocmd FileType stylus` in a .styl-file. It will show you registered autocmds for the filetype. Maybe it's there, but isn't the last one.

**Comment by aq2** [comment]
the only autocmd listed is `FileType stylus commentstring=//\ %s`  BUT i still get html comments!

**Comment by graywh** [comment]
Don't put the autocommand in the ftplugin file. Just set the option.

**Comment by aq2** [comment]
thanks @graywh  - that works!

sorry for my vim noobishness, but we got there in the end

**Comment by mfiano** [comment]
Sorry to resurrect the dead, but is it possible for this plugin to honor Lisp comments? Lines in most Lisp dialects are commented with 1-4 semicolons, depending on their intent. `commentstring` is obviously not enough to handle this. If I were to try un-commenting a line containing `;; Some comment`, this plugin produces `; ;; Some comment` instead.

**Comment by tpope** [comment]
Not possible. My understanding of Lisp is that the intent of one semicolon commenting out code, and multiple are for documentation. Commentary is focused on commenting out code so support for a single semicolon is generally sufficient.

**Comment by mfiano** [comment]
Fair enough.

That is incorrect about comments in Lisp. Documentation uses a different syntax (double-quoted strings in designated places). The number of semi colons used for comments depends on where they are located. 4 for the top of a file, 1 for inline comments at the end of a line, etc.

**Comment by tpope** [comment]
Oh right, there is no convention for commenting out code. But since it's generally a temporary affair it doesn't need a convention.
