### ISSUE TITLE
Python comment, good on windows, but with C style on Mac M1.

### ISSUE THREAD

**Issue by sloppydevil** [tpope/vim-commentary#153]
two laptops:
one workstation windows, one Mac M1. with the same config;
when use gcc to comment python files:
* for windows laptop, good;
* for mac laptop, bad (c style /* ... *. appeared);

note: I checked filetype, both good showing "filetype=python".

**Comment by tpope** [comment]
Sounds like you might be missing `filetype plugin indent on`.

**Comment by DexterAntonio** [comment]
I had this issue today. It is essential to put `filetype plugin indent on` in your `~/.vimrc` file. Running the command `filetype plugin indent on` after starting up vim will not resolve the commenting issue with Python.
