### ISSUE TITLE
Support for files with mixed languages

### ISSUE THREAD

**Issue by MarcelRobitaille** [tpope/vim-commentary#154]
Is there any support for files with multiple languages? With lots of nvim plugins moving to lua, I have a lot of lua code blocks in my `.vim` files:

```viml
lua <<EOF
...
EOF
```

In vim, my `commentstring` is set to `" %s`, but to comment in lua, it should be `-- %s`. Is there any way to achieve this?

This would also apply to code blocks in markdown files, lua code in LuaLaTeX, css in jsx, etc.

I looked through the issues and didn't see anything. Sorry if I missed it.

**Comment by tpope** [comment]
https://github.com/suy/vim-context-commentstring

**Comment by MarcelRobitaille** [comment]
That is exactly what I was looking for. Thank you so much.
