### ISSUE TITLE
How to comment empty lines?

### ISSUE THREAD

**Issue by RyannDaGreat** [tpope/vim-commentary#155]
I have the code:

```
def f(x):
    print(x)

    print(y)
```

but when commenting out the function, it gives 

```
# def f(x):
#     print(x)

#     print(y)
```

It skipped the empty line. I want this:

```
# def f(x):
#     print(x)
#
#     print(y)
```

How do I do this?

**Comment by tpope** [comment]
Not currently supported.

**Comment by RyannDaGreat** [comment]
@tpope But why? Most other editors do this...should I make a pull request?
