### ISSUE TITLE
vim-commentary set wrong comment when edit user's crontab file

### ISSUE THREAD

**Issue by eval-exec** [tpope/vim-commentary#156]
steps to reproduce:
`crontab -e`
![image](https://user-images.githubusercontent.com/46400566/156869741-9d714711-7319-4448-bd5f-e889cfd7855a.png)
then `gcc` in vim `NORMAL` mode
![image](https://user-images.githubusercontent.com/46400566/156869760-cbb21784-82cb-4f33-bca5-909dfc114e05.png)

crontab expect `#` as comment style like shell scripts, but it set it to `/* */`.
```
$ crontab -V
cronie 1.5.7
```

**Comment by tpope** [comment]
See the FAQ.
