### ISSUE TITLE
Installation described in Readme does not work

### ISSUE THREAD

**Issue by rojarand** [tpope/vim-commentary#157]
`git clone https://tpope.io/vim/commentary.git` ends with:
`
Cloning into 'commentary'...
fatal: unable to access 'https://tpope.io/vim/commentary.git/': server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
`

**Comment by chrisbra** [comment]
you need to update your ca-certificates. this is actually more a git issue and not specific to this repo. Check e.g. https://stackoverflow.com/questions/35821245/github-server-certificate-verification-failed to resolve

**Comment by tpope** [comment]
Yep, thanks. If it works for the GitHub URL and not the tpope.io URL, you can use that instead.
