### ISSUE TITLE
How to set the comment prefix

### ISSUE THREAD

**Issue by anqin** [tpope/vim-commentary#158]
Hi,

Is it possible to set the comment prefix? something like:

// test.cc
int MyFunc(int x) {
    std::cout << x << std::endl;
}

can be commented/uncommented multi-lines with "//":

// test.cc
// int MyFunc(int x) {
//    std::cout << x << std::endl;
// }

I think the "//" would be more friendly to CPP developers.

Thanks~

**Comment by tpope** [comment]
`setlocal commentstring=//\ %s`. Put this somewhere like `~/.vim/after/ftplugin/c.vim`.
