### ISSUE TITLE
Different custom keybinding

### ISSUE THREAD

**Issue by fritzrehde** [tpope/vim-commentary#160]
Hi, I am fairly new to Vim, so this might be an obvious question: 
Is there a way to use this plugin with a custom keybinding defined in .vimrc? I would like to map <leader><Space> to what gcc (toggle comment a line) does, is this possible? I read online that it has something to do with <Plug>, but I can't quite figure it out.
Thank you!

**Comment by tpope** [comment]
Map to `<Plug>CommentaryLine`. It's not documented but for Commentary and most other plugins you can generally figure it out by searching for `<Plug>` in the plugin file. https://github.com/tpope/vim-commentary/blob/3654775824337f466109f00eaf6759760f65be34/plugin/commentary.vim#L117
