### ISSUE TITLE
How to remapping this

### ISSUE THREAD

**Issue by Ryangithub10** [tpope/vim-commentary#161]
I was use this and i want remmap the key! I don't want to type `gcc`, i want to press `<ctrl> /` like other teks editor like vs code.
But i don't know how to remmap operator key. I hope you understand what i am saying beacuse my english still suck 😅

**Comment by k1ng440** [comment]
lua example: 
`vim.keymap.set("v", "<C-/>", "<Plug>Commentary", { noremap = true })`

vim config
```
  xmap <C-/>  <Plug>Commentary
  nmap <C-/> <Plug>Commentary
  omap <C-/> <Plug>Commentary
  nmap <C-/>c <Plug>CommentaryLine
  nmap <C-/>u <Plug>Commentary<Plug>Commentary
```
