### ISSUE TITLE
Should something like ``gc3w`` work?

### ISSUE THREAD

**Issue by RhvdG** [tpope/vim-commentary#162]
Suppose I want to comment out a number of words, but not an entire line, (when using Vim as a general text editor, to write books, this is a common occurrence), should something like ``gc3w`` work then? On my Vim configuration, it doesn't. Same with ``gc)`` to comment out until the end of the sentence, and so on. Tried visual, too (``vt.gc``), but no luck: only entire lines are commented-out each time.

**Workaround:** add ``vnoremap <leader>gc "cdi<!--<esc>"cpa--><esc>`` to .vimrc, visually select, then hit leader gc. (Without the noremap it needs two undos to undo.) Note that the c register is used, and that ``gcgc`` fails for comment blocks created like this, and obviously this only works with the ``<!--`` type of comment, but the map can probably be rewritten for many other types.

**Comment by tpope** [comment]
Commentary operates on whole lines only.
