### ISSUE TITLE
commentary does not properly detect (or use) known filetype

### ISSUE THREAD

**Issue by wosym** [tpope/vim-commentary#164]
I've used this plugin on several machines for quite some time now, and it works flawlessly on all filetypes I work with.

On one machine however, it does not appear to use the filetype properly. I'm not sure yet why. 

For example, `:set filetype?` returns `filetype=python`, which should be supported. However, it still adds C-type comments (/* --- */) when typing `gcc`

Not sure what's causing this bug. Is there a way to show what filetype commentary has detected and is using?

**Comment by tpope** [comment]
Commentary doesn't directly use `'filetype'` but rather `'commentstring'`, which is typically set by the ftplugin. My guess is you're missing `filetype plugin indent on` in your vimrc. (Many installs enable this in the system vimrc, so that's probably why the issue is specific to one machine.)
