### ISSUE TITLE
Vim commentary doesn't work on svelte.

### ISSUE THREAD

**Issue by abhiyandhakal** [tpope/vim-commentary#166]
`:Commentary` doesn't work on files with .svelte extensions.

**Comment by tpope** [comment]
Define "doesn't work".

**Comment by abhiyandhakal** [comment]
It doesn't comment stuff

**Comment by dshibanov** [comment]
In my case it also doesn't work

**Comment by jumski** [comment]
I confirm this behaviour - nothing happens when invoking `:Commentary` or **gcc** mapping

**Comment by tpope** [comment]
Seeing `/* line */` here. Which may not be right, but it is the global default.
