### ISSUE TITLE
Would a gc text object even make sense?

### ISSUE THREAD

**Issue by gfixler** [tpope/vim-commentary#17]
A few times I've caught myself absent-mindedly doing `digc` to delete the commented block I'm in. This makes as little sense as `digq` or `dig?`, but it did make me wish for a text object in commentary that allowed me to refer to the commented-out section I'm in. I realize it wouldn't be symmetrical; there can't be a text object for pre-commented or post-uncommented code, but I think it would be nice to do other things to code that _is_ commented, beyond simply uncommenting it. Thoughts?

I would also like `[gc` and `]gc` for hopping between commented blocks, but I don't want to get _too_ pushy in a single issue.

**Comment by sulgg** [comment]
> So contrary to what I was saying earlier, this was pretty straightforward once I decided not to worry about taking a count or visual mode. There's just one text object, `gc`, and it has outer `a` semantics. I also added a white lie `cgc` which changes with inner `i` semantics. This means `gcgc` is now "undo comment." I like the symmetry.
> 
> Note that multiple adjacent comments group together. This makes sense paired up with the fact we don't add comment characters to blank lines.

This is really cool but I realized this could be done once I got here. Is it possible to add help for this feature in commentary.txt?
