### ISSUE TITLE
No space after "//" in Rust when a line with only "//" appears in range

### ISSUE THREAD

**Issue by scanny** [tpope/vim-commentary#175]
Thanks so much for this plugin Tim, I've been using it for many years now :)

I'm seeing an odd behavior in Rust, selecting multiple lines in visual mode then `gc`; this comments fine:
```rust
struct A {
    // Alpha-struct
}

/* becomes this, as expected */

// struct A {
//     // Alpha-struct
// }
```

But this doesn't get the space after `//`:
```rust
struct A {
    //
}

/* becomes this */

//struct A {
//    //
//}
```

Usually this would occur in a situation like below where there's a single doc-comment with a summary line and then a paragraph:
```rust
struct Style {
    /// A character style.
    ///
    /// Very simple for now, but likely to grow. Encapsulating it is borderline just now but gives
    /// us headroom for it to grow without disrupting interfaces that use it.
    ///
    bold: bool,
    italic: bool,
}
```

I notice it when I'm commenting out whole sections of a file, so not usually. It seems like a single line like that will cause this behavior for the whole block, so perhaps in some preliminary step where it scans the whole block to decide what column to insert on or something like that.

**Comment by tpope** [comment]
Easy enough to address that edge case. It's kind of weird the inner comment affects commenting at all.

**Comment by scanny** [comment]
You 'da man Tim! :)
