### ISSUE TITLE
//-comments in a C file

### ISSUE THREAD

**Issue by ghost** [tpope/vim-commentary#30]
i remember using a different commenting plugin which normally would insert // and had a 'multiline' operator that would insert /\* and */ instead. can haz something like that? or do i just need to tweak something in my .vimrc?

**Comment by capndave** [comment]
Where is this `after/ftplugin/c.vim` that's mentioned above? I just need to set my comments to // or /* for all files.

**Comment by tpope** [comment]
Create it in `~/.vim` (or `~\vimfiles` on Windows).

**Comment by chrisbra** [comment]
> Where is this after/ftplugin/c.vim that's mentioned above? I just need to set my comments to // or /* for all files.

Note, this is a filetype specific setting, so the above will only set it for `C` files.
