### ISSUE TITLE
Support of block comment

### ISSUE THREAD

**Issue by introom** [tpope/vim-commentary#39]
@tpope 
Could commentary support block comment in visual mode?
additional information could be provided with buffer vars such as, b:block_cms, b:block_enabled

This is extremely useful when dealing with file types like css (the line based comment of css is way too disturbing for a block).
For example:
![1bq2e](https://cloud.githubusercontent.com/assets/669045/5354676/27337554-7fc6-11e4-9569-bfcb195ccc66.jpg)

Regards

**Comment by greduan** [comment]
+1, tcommentary.vim has this implemented through alternative maps.

**Comment by tpope** [comment]
And if you comment out 2 paragraphs and then try to uncomment one, what happens? Does tcommentary successfully move the delimiters to surround the other paragraph?

**Comment by greduan** [comment]
Good point. That could be done but it feels like it may be out of this plugin's scope, because of complexity.

**Comment by tpope** [comment]
Since the point is *temporarily* commenting out code, I'm not going to sacrifice functionality for aesthetics, nor introduce the complexity of an additional map. I would of course entertain the possibility of a best of both worlds map, but I don't see that as feasible to implement.

**Comment by uschtwill** [comment]
This is so weird, please bear me out: 

So apparently `vim-commentary` doesn't do block comments, right? Only that it does over here. I have a Logstash config split in like 10 files, and I am trying to toggle whole sections/files with `vim-commentary`. For some files it neatly just inserts a `#` at the start of the line (which makes me very happy, thank you!) but for others it wraps every line like so: `/* line */` (which just makes Logstash fail miserably on startup). 

The worst part is that I can absolutely *not* discern/reproduce why for some files it's doing it the one way versus the other way for the others.

I am pretty new to `vim` and use [maximum-awesome](https://github.com/square/maximum-awesome) to get started. I will also include the `vundle` plugin list, maybe your spotting something that is colliding with `vim-commentary` and thus causing that behaviour.

Please help, this is driving me insane!

Plugins:
```
" Plugins here are part of the CORE Maximum Awesome setup
" Do NOT add bundles to this list, as they might get removed when you upgrade
" Maximum Awesome.
" Please create ~/.vimrc.bundles.local and add any extra bundles you want there
Plugin 'VundleVim/Vundle.vim'
Plugin 'airblade/vim-gitgutter'
Plugin 'altercation/vim-colors-solarized'
Plugin 'austintaylor/vim-indentobject'
Plugin 'christoomey/vim-tmux-navigator'
Plugin 'juvenn/mustache.vim'
Plugin 'kchmck/vim-coffee-script'
Plugin 'ctrlpvim/ctrlp.vim'
Plugin 'leafgarland/typescript-vim'
Plugin 'majutsushi/tagbar'
Plugin 'rking/ag.vim'
Plugin 'garbas/vim-snipmate'
Plugin 'MarcWeber/vim-addon-mw-utils'
Plugin 'tomtom/tlib_vim'
Plugin 'nathanaelkane/vim-indent-guides'
Plugin 'nono/vim-handlebars'
Plugin 'pangloss/vim-javascript'
Plugin 'wookiehangover/jshint.vim'
Plugin 'scrooloose/nerdtree'
Plugin 'scrooloose/syntastic'
Plugin 'slim-template/vim-slim'
Plugin 'tpope/vim-bundler'
Plugin 'tpope/vim-commentary'
Plugin 'tpope/vim-cucumber'
Plugin 'tpope/vim-dispatch'
Plugin 'tpope/vim-endwise'
Plugin 'tpope/vim-fugitive'
Plugin 'tpope/vim-pastie'
Plugin 'tpope/vim-ragtag'
Plugin 'tpope/vim-rails'
Plugin 'tpope/vim-repeat'
Plugin 'tpope/vim-surround'
Plugin 'tpope/vim-unimpaired'
Plugin 'tpope/vim-vividchalk'
Plugin 'eventualbuddha/vim-protobuf'
Plugin 'vim-ruby/vim-ruby'
Plugin 'vim-scripts/Align'
Plugin 'vim-scripts/greplace.vim'
Plugin 'vim-scripts/matchit.zip'
Plugin 'htacg/tidy-html5'
Plugin 'robbles/logstash.vim'
```

**Comment by chrisbra** [comment]
for the files, where your commentstring is wrong, simply do `:setlocal commentstring=#\ %s`

**Comment by uschtwill** [comment]
# O_O 
Magic!!!

Okay. But how and why? How/why is that variable different for some files? And why is this issue proclaiming `vim-commentary` doesn't do comment blocks, when it does?

My confusion was ...transformed - but it is still there.

**Comment by vheon** [comment]
> How/why is that variable different for some files?

To know where was set the last time try `verbose set commentstring?` in the file where you have the wrong commenting.

> And why is this issue proclaiming vim-commentary doesn't do comment blocks, when it does?

Because it doesn't. The fact that it can use "block style" comment like `/* ... */` it doesn't mean that it can do block comments. If it were if multiple line where selected to be commented out it should place `/*` just before the first line and `*/` just after the last one, instead it comment each line with `/* <line> */`.

**Comment by uschtwill** [comment]
Of course, you are correct - those are very different things indeed.

But all is well now! Thanks for your time, @chrisbra and @vheon!

**Comment by dragonofdeath** [comment]
hp
1. Not sure whats going on here. In the screenshot i see icon for mobile, but the browser is desktop for sure. Does he still have that problem?
2. Changed some info with tokens , but the footer is straight copy from bsf, the info is different from what we have now in schools so please give me more info of what should be here. 
3. waiting
Sidebar blocks
1. The font we are using here doesn't have "bold". Using font "Helvetica". done
2. done
3. done
4. done
In general
*"margin between the pager and the rest of the sidebar up is unnecessary big. See below as example." - Moved it up a bit. But for some slides its still too far and for some others it get's too close.
*thick border done

**Comment by vegerot** [comment]
> And if you comment out 2 paragraphs and then try to uncomment one, what happens? Does tcomment successfully move the delimiters to surround the other paragraph?

Came here to ask this same question.  Your point here successfully convinced me this is a much [harder task](https://xkcd.com/1425/) than I had considered.  Thanks for your excellent response!
