### ISSUE TITLE
Support comments, that have no spaces following...

### ISSUE THREAD

**Issue by chrisbra** [tpope/vim-commentary#40]
Hi, this just came up at [reddit.com](http://www.reddit.com/r/vim/comments/2vj4l9/vimcommentary_on_existing_external_comments/)
In summary, commentary doesn't toggle comments, that don't have a space in between. E.g. this:

    

won't be properly toggled in a html file.

This could happen because of an application injecting comments or some other user adding comments (who is not using Vim). 
I made a patch [here](https://gist.github.com/chrisbra/1832a5eece434ee1616c#file-gistfile1-txt)

**Comment by qstrahl** [comment]
This issue has been raised many times. The short answer is it ain't
changing.

**Comment by chrisbra** [comment]
Look, I even made a patch, so I think, it deserves at least a long answer....

**Comment by qstrahl** [comment]
See issues #3, #32, and #33

**Comment by chrisbra** [comment]
Thanks. But how am I supposed to handle this situation then? I haven't seen a solution to this problem in those issues

**Comment by tpope** [comment]
#33 does have a workaround.

**Comment by chrisbra** [comment]
Doesn't work for mixed style comments, which is all what this issue was about.

**Comment by chrisbra** [comment]
But I close this issue. Doesn't make sense to discuss an issue, that no one is interested into.

**Comment by chrisbra** [comment]
I forked it and fixed it myself.

**Comment by tpope** [comment]
If only you could do the same for your attitude :frowning:

**Comment by chrisbra** [comment]
I didn't want to sound harsh, so let me apologize in case I was. I just wanted a bug getting fixed.

**Comment by ReneFroger** [comment]
I agree with @chrisbra

**Comment by jceb** [comment]
@chrisbra is issue comes up every once i a while, see also #3, #32.  I maintain a branch with a patch, feel free to use it: https://github.com/jceb/vim-commentary/tree/support_for_legacy_comments

**Comment by tpope** [comment]
So elsewhere I have discussed how this can cause problems with incorrect indenting. One solution I would be satisfied with would be to treat the entire selection holistically. That is, say you try to uncomment the following:

```
#one
#  two
```

I would accept a solution that left both spaces before `two`, while not breaking the existing behavior when all lines have spaces.

**Comment by chrisbra** [comment]
So whenever within a range of comments one line is contained, that has no space following, then delete for the all lines only the commentchar (without the space).
I would have thought otherwise, to always remove the space, except for the case, when a space is missing...
I can make a patch.

**Comment by tpope** [comment]
Yeah, always removing the space can result in inconsistent indenting, which has been the source of my resistance.

**Comment by chrisbra** [comment]
Here we [go](https://gist.github.com/chrisbra/0ba9df9011ddc38e7181)

**Comment by tpope** [comment]
Will give this a spin. Feel free to ping next week if I haven't followed through.

**Comment by akkartik** [comment]
I just came across this thread and, at the risk of picking at an old scab, I wanted to share the solution I've been using for over a decade. What I do is to distinguish between lines commented out with this plugin and regular comments. For example, in C++ my tweak below comments out code using a leader of `//?` rather than `//`. As a result I can select large ranges and uncomment all debug prints (because that's my primary use for this feature) in them without affecting regular comments. As a result I can also be more aggressive about handling whitespace padding and so on. Here's the function I use:

```vim
function! Comment() range
  for l:l in range(a:firstline, a:lastline)
    call setline(l:l, b:cmt_head.getline(l:l))
  endfor
endfunction
command! -range Cmt <line1>,<line2>call Comment()

function! Uncomment() range
  let l:cmt_len = len(b:cmt_head)
  for l:l in range(a:firstline, a:lastline)
    let l:line = getline(l:l)
    if (l:line[0 : l:cmt_len-1] == b:cmt_head)
      call setline(l:l, l:line[l:cmt_len :])
    endif
  endfor
endfunction
command! -range UnCmt <line1>,<line2>call Uncomment()
```

To make this work for C/C++, you'll need to add this line to say `after/ftplugin/c.vim`:

```
let b:cmt_head = "//? "
```

(The trailing space is optional, but I like it.) Similarly for other languages.

**Comment by vim-ml** [comment]
ping

**Comment by chrisbra** [comment]
ping

**Comment by jceb** [comment]
ping

**Comment by tpope** [comment]
I'm actually starting to like the idea of omitting the leading space to distinguish commented out code from documentation. Maybe in 2.0...

**Comment by jceb** [comment]
Great, thank you!

**Comment by suy** [comment]
Works awesome, thank you. :smiley:
