### ISSUE TITLE
gcgc/gcu don't uncomment lines which are separated by blank lines

### ISSUE THREAD

**Issue by kiryph** [tpope/vim-commentary#41]
# first block
    # still junk of first code block

    # second code block
    # here we are
    #  further code in second code block

I'd like to uncomment with `gcu` only the second code block not the first one as well. What do you think about it?

**Comment by qstrahl** [comment]
You could just do `gcap`

**Comment by kiryph** [comment]
True. I didn't see it. Thanks for sharing.
