### ISSUE TITLE
Erroneous comment string with xdefaults filetype

### ISSUE THREAD

**Issue by dbb** [tpope/vim-commentary#47]
When editing either `~/.Xdefaults` or `~/.Xresources`, the filetype is set to `xdefaults` according to the output of `:set ft?`. By default, commentary uses CSS style comments, i.e. `/* */`. So I consulted the readme and added the following line to my `.vimrc`:

```
autocmd FileType xdefaults set commentstring=!\ %s
```

However, after re-sourcing my config and even restarting vim, I'm still getting the CSS-style comments. I was hoping you might be able to shed some light on this. Thanks in advance.

**Comment by dbb** [comment]
Forgot to mention that `:set commentstring?` reports `commentstring=/*%s*/`, which seems to be in direct conflict with the line in my `.vimrc`.

**Comment by tpope** [comment]
Since `ftplugin/xdefaults.vim` (bizarrely) enforces the global default of `/*%s*/`, you need to define your autocommand *after* `filetype plugin indent on`, so that the execution order will be correct.
