### ISSUE TITLE
comment works, uncomment leaves partial comment

### ISSUE THREAD

**Issue by shanemikel** [tpope/vim-commentary#48]
This has worked for me for a while, today I noticed a bug

starting with this:
<code>
#tag {

    some: css;

}
</code>

commenting changes it to this:
<code>
#tag {

    /* some: css; */

}
</code>

uncommenting changes it to this:
<code>
#tag {

    * some: css; *

}
</code>
When I noticed it, I updated my plugins, but it didn't help.

**Comment by tpope** [comment]
That's odd. Did you toggle any settings in your vimrc recently?

**Comment by shanemikel** [comment]
Nothing relevant AFAIK.. Added a plugin, but just disabled it to check the bug

**Comment by shanemikel** [comment]
I changed the commentstring for css to '//\ %s', and I'd rather use line comments anyway, but I figured you'd wanna know.  If you need more info just ask.

**Comment by tpope** [comment]
I can confirm `/*%s*/` still works for me.

**Comment by shanemikel** [comment]
Hmm. Is it just me, or do //%s and //\ %s both add a space?

**Comment by tpope** [comment]
By design yes. Discussed ad nauseum in other issues.

**Comment by shanemikel** [comment]
Just deleted all plugins and vimrc.  Installed fresh Vundle and vim-commentary with no other configuration, yet bug persists.

vim 2:7.4.640 on f22
