### ISSUE TITLE
filetype invalid after installing the YCM

### ISSUE THREAD

**Issue by bwangel23** [tpope/vim-commentary#50]
hello,everyone! i meet a question about this plugin.

I use the pathogen to manage my plugin, and put the all plugins in the bundle dir. After installing the YouCompleteMe plugin, run the `gcc` in any type of file, will be annotated into `/**/`

like this picture:
![commentary_ques](https://cloud.githubusercontent.com/assets/11701497/9153451/75a95794-3e89-11e5-8b77-66d3dbc53c40.png)

**Comment by vheon** [comment]
what is the output of `:verbose set commentstring?`.

**Comment by bwangel23** [comment]
![commentary_ques2](https://cloud.githubusercontent.com/assets/11701497/9171305/f2c23958-3f9c-11e5-82fb-d43a8a520b69.png)

in a python file, and it is /*%s*/

**Comment by vheon** [comment]
That is why you get that behaviour. You have to look why the ftplugin didn't kick in. Do you have `filetype plugin on` in your vimrc?

**Comment by bwangel23** [comment]
This is a ptyhon code file.

I set the `filetype plugin on`, and still cann't slove this question.
