### ISSUE TITLE
Add `$#` syntax for .hamlet

### ISSUE THREAD

**Issue by wolftune** [tpope/vim-commentary#53]
Although html style `<!--    -->` works for .hamlet in the Shakespeare templating language hamlet, the ideal syntax is to simply prepend `$#` to a line. It would be great if vim-commentary would support that for .hamlet files.

**Comment by xaizek** [comment]
vim-commentary doesn't configure things like that, filetype plugins or users do the same way as described in [faq](https://github.com/tpope/vim-commentary#faq).

**Comment by wolftune** [comment]
@xaizek okay thanks
