### ISSUE TITLE
comment or uncomment all lines in a fold

### ISSUE THREAD

**Issue by migueldvb** [tpope/vim-commentary#55]
I would like to comment all lines in a fold when it is closed. I have tried the `gcc` and `Visual}gc` 
combinations but it does not work in `neovim` nor `vim`. Is there any way to comment a closed fold?

**Comment by qstrahl** [comment]
There are motions to move you to the beginning and end of a fold; `[z and ]z`. You should be able to `[zgc]z` inside a fold. Give it a shot.

**Comment by migueldvb** [comment]
Thanks, this works well but only when there are on parts of the text
in the fold that are already commented...

**Comment by qstrahl** [comment]
Not sure what you mean. What's the issue?

**Comment by migueldvb** [comment]
I'm trying to find a minimal example but apparently it works
all the time except for my complicated fold structure. Will try to
figure out the problem.

**Comment by tpope** [comment]
Gonna go out on a limb here and assume the problem isn't with commentary, until demonstrated otherwise.
