### ISSUE TITLE
Provide an option to remove backwards compatible mappings

### ISSUE THREAD

**Issue by norcalli** [tpope/vim-commentary#57]
The mappings are creating delays in my maps with shared prefixes, and I'm not sure of a good way to remove them. Perhaps an option that we could set to disable those mappings would be a good compromise.

**Comment by vheon** [comment]
The backward compatible are the one with `\\`? then just put `let g:commentary_map_backslash = 0` in your vimrc and you're good to go.

**Comment by norcalli** [comment]
Thanks, didn't know about that option. There's always something, haha.
