### ISSUE TITLE
Issue with HTML files

### ISSUE THREAD

**Issue by rafaelrinaldi** [tpope/vim-commentary#59]
For some reason `vim-commentary` wraps my HTML tags with `/* ... */` instead of `<!-- ... -->`. I'm going with the default configurations, no changes. What am I doing wrong?

**Comment by tpope** [comment]
You probably don't have `:filetype plugin indent on`?

**Comment by rafaelrinaldi** [comment]
@tpope Oh, you're right. Thanks!
