### ISSUE TITLE
please support tag comment

### ISSUE THREAD

**Issue by butterflyfish** [tpope/vim-commentary#63]
[plugin]( https://github.com/mvolkmann/vim-tag-comment) have it. is it possible to let vim-commentary to support it ? I don't like to add another map except 'gc'

**Comment by tpope** [comment]
Supporting commenting over any arbitrary motion like that is way more complicated than the handful of behaviors that plugin supports. And I could hardly care less about "ugly and excessive" when it comes to temporarily commenting out code. So no, it's not coming unless you implement it.
