### ISSUE TITLE
Support for JSX...

### ISSUE THREAD

**Issue by ehzShelter** [tpope/vim-commentary#68]
Cannnot handle comment for .jsx files...Though JSX is confusing for vim..
Is there any hacky way to solve this?

**Comment by vheon** [comment]
Look at the [FAQ](/tpope/vim-commentary#faq)

**Comment by ehzShelter** [comment]
JSX elements cannot be commented out by using standard // or /* */ commenting. Normally {/* */} is used instead.

autocmd FileType jsx  setlocal commentstring={/*\ %s
 autocmd FileType javascript.jsx  setlocal commentstring={/*\ %s

Tried both
Not working.....

Is there any problem with my expression...

**Comment by vheon** [comment]
I briefly looked into jsx and from the turorial it seems that `//` works just fine for line comment :confused: Have I missed something?

**Comment by ehzShelter** [comment]
Yeah ...true // works fine for jsx ...But sometimes ...I need other style...
![screenshot 13](https://cloud.githubusercontent.com/assets/12381692/14233383/abf3d99e-f9e8-11e5-866e-96baa5037c59.png)

**Comment by tpope** [comment]
For the autocommand to work you need to invoke it *after* `filetype plugin on`. Or just put `set commentstring=...` in `after/ftplugin/jsx.vim`.

**Comment by thenickcox** [comment]
Just to follow up on @tpope's solution, this works by setting

`set commentstring={/*\ %s\ */}`

in `~/.vim/bundle/vim-jsx/after/ftplugin/jsx.vim` (or wherever your bundle dir is).

**Comment by ehzShelter** [comment]
As tpope described... by the way... tcomment plugin for JSX is much better as jsx two different comment depending on context, inline comment inside JSX or wahtever.. Tcomment plugin gives much modularity

**Comment by Arelav** [comment]
`autocmd FileType javascript.jsx setlocal commentstring={/*\ %s\ */}`

**Comment by ehzShelter** [comment]
Great...

**Comment by afk-mcz** [comment]
Is there any way to easily toggle between two types of comments?

In jsx files it is common that you have a block of JS and then a block of JSX, on the JSX block the commntstring `{/*\ %s\ */}` works fine, but in the JS block `/*\ %s\ */` would be better, example: 

import React, { Component } from 'react';

```jsx
class Test extends Component {
    render() {
        /* console.log('test');*/
        return (
            <div>
                {/*<span>test</span>*/}
                <span>test</span>
            </div>
        )
    }
}

export default Test;

```

**Comment by nightsdark** [comment]
Yes maybe, I had this solution working yesterday and it broke inside the current project. My approach was to use (vim-commentary and vim-context-commentstring)  
install both pluggins:
- Use no settings to commentary
- Use these settings in context-commentstring:
    let g:context#commentstring#table = {}

    let g:context#commentstring#table.vim = {
                \ 'vimLuaRegion'     : '--%s',
                \ 'vimPerlRegion'    : '#%s',
                \ 'vimPythonRegion'  : '#%s',
                \}

    let g:context#commentstring#table.html = {
                \ 'javaScript'  : '//%s',
                \ 'cssStyle'    : '/*%s*/',
                \}

    let g:context#commentstring#table.jsx = {
                \ 'jsxStatment'    : '/*%s*/',
                \ 'jsxRegion'     : '{/*%s*/}',
                \}
    let g:context#commentstring#table.xhtml = g:context#commentstring#table.html

table.jsx is the (new) part the rest exists already in the vim-context-commentstring bundle/autoload/context/commentstring.vim 
you have to add it to that file, or copy the whole thing to into you're vimrc.

Next, read the docs for vim-context-commentstring or just use zS in your jsx file to see what your region your cursor is in this relies on vim-scriptease pluggin 

it might be working by now, but I had to check filetype assignment in react-jsx
    autocmd! BufRead,BufNewFile *.{jsx,jx,js} setlocal filetype=javascript.jsx
may need to add javascript.jsx to machit plugin configuration and emmet or other programs that won't know anymore the new .js javascript.jsx filetype.

**Comment by Arelav** [comment]
@nightsdark Thanks for the suggestion to right direction.
I created [pull request](https://github.com/suy/vim-context-commentstring/pull/1) to the suy/vim-context-commentstring with React comments support for JS and TS both.

Who wants to start using right now can install the plugin from my [fork](https://github.com/Arelav/vim-context-commentstring).

**Comment by Arelav** [comment]
Also, I added Vue support from another fork of this project but no PR was created by the author so I included this code also to my PR.

**Comment by nightsdark** [comment]
@Arelav, taking a look at the contributions, I had success and some issues, some comment regions where not un-commenting. I am now able to control the comments with 
````bash 
let g:context#commentstring#table['javascript.jsx'] = {
			\ 'jsComment' : '// %s',
			\ 'jsImport' : '// %s',
			\ 'jsxStatment' : '// %s',
			\ 'jsxRegion' : '{/*%s*/}',
\}
````

***_for_ javascript this made them look like _normal_ js comments***

```` // import 'React', component from 'react' ````

**comments** for JSX within the render block looks like

````javascript 
JSX code {/* <div><a><img src="#2.jpg" /></a> </div>  */}

If I run into any more, should I PR the suy/vim-context-commentstring main repo?

**Comment by Arelav** [comment]
@nightsdark I changed my vim settings and the region was changed to jsxRegion.
So I created new PR including the changes you suggested.
https://github.com/suy/vim-context-commentstring/pull/3/commits

**Comment by nightsdark** [comment]
@Arelav I gave it a look and it seems fine. You have added new support for Typescript too. I see you also have a jsxTag (context). I will try find a jsxTag, I haven't found one yet. Although I have an xmlTag and xmlTagBlock. for the return statement.

**Comment by Arelav** [comment]
I still using the original plugin because the previous time my PR was approved very fast. But this time it takes time and me considering to start using my fork instead. You are welcome to create PR or just leave me a comment what is missing for you and I'll add to my fork.

**Comment by afk-mcz** [comment]
Do I have to do something extra appart from installing `vim-context-commentstring` ? 

My `commentstring` changes on the `import` section of my file, byt everywhere it uses the JSX `commentstring` instead of the JS

**Comment by Arelav** [comment]
@afk-mcz It depends to JS/JSX syntax plugin you are using.

It's few syntax plugins existing.

Also probably you will want to change `autocmd BufNewFile,BufRead` in your vimrc. You can see the reference in my comment from Jun 11.

Also very helpful temporary to enable the plugin `tpope/vim-scriptease` by `zS` shortcut you can see which region defined in special line.

**Comment by afk-mcz** [comment]
Where do you put your config for changing the `let g:context#commentstring#table['javascript.jsx']` I tried putting it on my vimrc and it shows as undefined, and on the `autoload/context/commentstring.vim` file it mar's the variable as undefined when I open a file

**Comment by nightsdark** [comment]
@afk-mcz --- I'm using vim-handlebars plugin as well and it works with this in bundle/vim-handlebars/ftdetect/handlebars.vim
```vim 
if has("autocmd")
  au BufNewFile,BufRead *.{handlebars,hb,hbs,hbt,html}{,.erb} set ft=handlebars.html syntax=handlebars | runtime! ftplugin/handlebars.vim ftplugin/handlebars*.vim ftplugin/handlebars/*.vim
endif
```
and this for the bundle/vim-jsx/ftdetect/javascript.vim
```vim 
 """""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Vim ftdetect file
"
" Language: JSX (JavaScript)
" Maintainer: Max Wang <mxawng@gmail.com>
"
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

" Whether the .jsx extension is required.
if !exists('g:jsx_ext_required')
  let g:jsx_ext_required = 1
endif

" Whether the @jsx pragma is required.
if !exists('g:jsx_pragma_required')
  let g:jsx_pragma_required = 0
endif

let s:jsx_pragma_pattern = '\%^\_s*\/\*\*\%(\_.\%(\*\/\)\@!\)*@jsx\_.\{-}\*\/'

" Whether to set the JSX filetype on *.js files.
fu! <SID>EnableJSX()
  if g:jsx_pragma_required && !exists('b:jsx_ext_found')
    " Look for the @jsx pragma.  It must be included in a docblock comment
    " before anything else in the file (except whitespace).
    let b:jsx_pragma_found = search(s:jsx_pragma_pattern, 'npw')
  endif

  if g:jsx_pragma_required && !b:jsx_pragma_found | return 0 | endif
  if g:jsx_ext_required && !exists('b:jsx_ext_found') | return 0 | endif
  return 1
endfu

autocmd BufNewFile,BufRead *.jsx let b:jsx_ext_found = 1
autocmd BufNewFile,BufRead *.jsx set filetype=javascript.jsx
autocmd BufNewFile,BufRead *.js if <SID>EnableJSX() | set filetype=javascript.jsx | endif
```
put this in your vimrc
```vim
  let g:context#commentstring#table['javascript.jsx'] = {
            \ 'jsComment' : '// %s',
            \ 'jsImport' : '// %s',
            \ 'jsxStatment' : '// %s',
            \ 'jsxRegion' : '{/*%s*/}',
            \}
let g:context#commentstring#table['handlebars.html'] = {
            \ 'hbsInside' : '{{!--*%s*--}}',
            \}
```
these are appended to the context comment string table you should be able to comment the code based on the context _or_ region within the file and you have exit vim you may have to exit vim not just source vim to see this effect.

**Comment by coderek** [comment]
Another way is to install another comment tool like nerd-commenter. Then you can have different bindings for one file.

**Comment by aquadesk** [comment]
```" JSX commentary
if exists('g:context#commentstring#table')
  let g:context#commentstring#table['javascript.jsx'] = {
              \ 'jsComment' : '// %s',
              \ 'jsImport' : '// %s',
              \ 'jsxStatment' : '// %s',
              \ 'jsxRegion' : '{/*%s*/}',
              \}
endif
```

**Comment by Aasim-A** [comment]
Hi all, if anybody is using `Treesitter`, `vim-context-commentstring` will not work with it, use this awesome [plugin](https://github.com/JoosepAlviste/nvim-ts-context-commentstring) instead.

**Comment by magidandrew** [comment]
I'm using tim pope's "vim-commentary". This is all I had to do:

I created `commentary.lua` in my `after` directory. Then I just included this in the file:
```
vim.api.nvim_create_autocmd("FileType", {
  pattern = {"typescriptreact", "javascriptreact"},
  callback = function()
    vim.bo.commentstring = "{/* %s */}"
  end,
})
```

works like a charm.
