### ISSUE TITLE
Conditionally comment single or multiple lines

### ISSUE THREAD

**Issue by reubano** [tpope/vim-commentary#72]
I have the following mapping in `vimrc`: `nmap <D-/> gc`. Unfortunately, this only works on multiple visually selected lines.  The solution is to map to `gc$`, but that having 2 mappings to comment text doesn't seem correct. Is there a way to conditionally map to `gc` or `gc$` that works in the following cases?

 - comment current line
 - comment 1 visually selected line
 - comment 2 or more visually selected lines

**Comment by tpope** [comment]
If you want both normal mode and visual mode, you'll need both an `nmap` and an `xmap`, full stop.

**Comment by reubano** [comment]
Finally figured it out:

```
imap <D-/> <Esc>gc$
nmap <D-/> gc$
vmap <D-/> gc
```
