### ISSUE TITLE
Bug when commenting with a search motion

### ISSUE THREAD

**Issue by cranej** [tpope/vim-commentary#73]
When commenting with search motion, it comments one line less than expected. Say I have the below code:

    fun a()
    {
        some code
        more code
    }

Put cursor on `fun` and run `gc/}<CR>`, it only comments out the first 4 lines which I expect it to comment the last line '}' also.

**Comment by xaizek** [comment]
Tried that and found one additional condition to reproduce the bug: search match must be at the first column. Commenting with <kbd>gc/}&lt;CR&gt;</kbd> works as expected for this:
```
fun a()
{
    some code
    more code
 }
```

**Comment by cranej** [comment]
Just found `y/}<CR>` does not include the last line neither if the '}' is at the first column.  So maybe this is not a bug of this plugin... or even not a bug at all.  But I'm not quite understanding why Vim behaves like this...

**Comment by tpope** [comment]
As indicated in `:help /`, `/` is an exclusive motion and does not include the match in the range.

**Comment by cranej** [comment]
Yes it's a by design behavior in Vim.  In this case `gc/}/e<CR>` does the trick.
