### ISSUE TITLE
commentary is unbearably slow for certain commentstrings

### ISSUE THREAD

**Issue by anntzer** [tpope/vim-commentary#74]
```
$ (for i in $(seq 1000); do echo $i; done) >/tmp/foo.py
```
(commentstring for python files: `# %s`)
Selecting and commenting everything is ~instantaneous.

but
```
$ (for i in $(seq 1000); do echo $i; done) >/tmp/foo.tex
```
(commentstring for tex files: `%%s`)
Selecting and commenting everything hangs vim for ~10s.

**Comment by chrisbra** [comment]
cannot reproduce. You should [profile Vim](http://stackoverflow.com/a/12216578/789222) and see, where it spends most time:

**Comment by anntzer** [comment]
Indeed, I can't reproduce it anymore either.  Closing for now, will reopen if it occurs again...
