### ISSUE TITLE
Custom Comment for fortran

### ISSUE THREAD

**Issue by schmoni** [tpope/vim-commentary#76]
Hi, 
I am quite new to vim and after watching some tutorials, your plugin seems to be very useful to me. 
I use fortran as my primary language, files are named *.f90
Unfortunately, your plugin does not automatically support commentary in this case. 
It should put (/remove) a ! at the beginning of the line in question. 
In your FAQ it says to adjust commentstring: "autocmd FileType apache setlocal commentstring=#\ %s"
where do i add this line of code, what do i have to replace "FileType" with and what do i set commentstring to?
I would be very thankful for your help.
Greetings from Hannover, Germany

**Comment by nathanmusoke** [comment]
I'm surprised by this issue -- I use vim-commentary with Fortran and don't recall having to do anything to get it working. Does your installation work with other filetypes?

**Comment by schmoni** [comment]
Ok, apparently I did something wrong yesterday. I tried it again today and it works just fine. Thanks :)
