### ISSUE TITLE
Wrong commenting on 'Xdefaults' file type

### ISSUE THREAD

**Issue by Chinggis6** [tpope/vim-commentary#85]
Hi,

Both `.Xresources` and `.Xdefaults` files are being treated by vim as `xdefaults` file type.

But `gcc` surrounds the line with `<!-- --->` HTML comment tags / notations instead of `!` bang.

Thanks to the notice, I already added in my `.vimrc`

    " Correct commenting on .Xdefaults and .Xresources
    autocmd FileType xdefaults setlocal commentstring=!\ %s

to comment the lines properly, else it would result in error when the file is read.

It's not that the filetype is not supported but the commenting is wrong.

Please consider correcting it.

Awesome plugin,
Thanks for consideration.

To add, I somewhere read that Spacemacs' comment insertion is based on this plugin, but I tested Spacemacs does the commenting correctly on this file type (which is `Conf[Xdefaults]`), so it's probably noticed and fixed already in Spacemacs Evil.

**Comment by chrisbra** [comment]
vim-commentary relies on the fact, that the filetype is actually correct. Changing filetype defaults is out of the scope for this plugin. So your autocommand is the correct solution.

**Comment by tpope** [comment]
Yeah, the problem is with the included `ftplugin/xdefaults.vim`. You can reach out to the maintainer noted at the top of the file.
