### ISSUE TITLE
Any special comment shortcuts for python like #NOQA and etc?

### ISSUE THREAD

**Issue by eduOS** [tpope/vim-commentary#88]
For example I sometimes need some comments like `# pylint: disable=not-callable` or just `# NOQA` appending to the line to prevent showing the alert, possible to integrate?

**Comment by tpope** [comment]
You can maybe fiddle with `'commentstring'` or `b:commentary_format` to achieve the results you want.

**Comment by eduOS** [comment]
OK, thanks.
