### ISSUE TITLE
Dash lost when removing comments

### ISSUE THREAD

**Issue by kurkale6ka** [tpope/vim-commentary#92]
Start with: (`:se cms=#%s`)

```
#- Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor
#  incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis
#  nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
#  Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu
#  fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in
#  culpa qui officia deserunt mollit anim id est laborum.
```
Now, use `gcu` or `gcip` to destroy the dash
`gcc` works

I noticed this while working with yaml files. The position of the dash seems important. In the last line it doesn't do anything

**Comment by kurkale6ka** [comment]
Also, with `# -` it works. Only fails when they are stuck together (`#-`)

**Comment by tpope** [comment]
This appears to have been fixed by by89f43af18692d22ed999c3097e449f12fdd8b299.
