### ISSUE TITLE
How is it possible to customize keybindings?

### ISSUE THREAD

**Issue by mrbig033** [tpope/vim-commentary#98]
I tried using the plugs on the plugin file, no result. 

I'm using `NVIM v0.2.3-879-gce3bc12e2 Build type: RelWithDebInfo`.

**Comment by tpope** [comment]
The `<Plug>` maps should work fine.

**Comment by mrbig033** [comment]
I understand most Vim users are programmers or IT people, but I'm not yet, so could give me an example of how that could work? Thanks.

**Comment by tpope** [comment]
There was a deleted comment expressing confusion so here's an explicit example defining maps on the default `gc`.

```vim
" Visual mode
xmap gc <Plug>Commentary
" Normal mode
nmap gc <Plug>Commentary
" Normal mode, current line
nmap gcc <Plug>CommentaryLine
" Operator pending mode (this lets you do e.g. `dgc` to delete a block of comments)
omap gc <Plug>Commentary
" Special case cgc (you can skip this one, but then `cgc` will also delete an extra blank line)
nmap cgc <Plug>ChangeCommentary
```
